In [33]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, Binarizer, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler
df=pd.read_csv("C:/Users/rajpu/OneDrive/Desktop/b/pima-indians-diabetes.csv")
df


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Class  
0                       0.627   50      1  
1                       0.351   31      0  
2                       0.672   32      1  
3                       0.167   21      0  
4                       2.288   33      1  
..                        ...  ...    ...  
763                     0.171   63      0  
764                     0.340   27      0  
765                     0.245   30      0  
766                     0.349   47      1  
767                     0.315   23      0  

[768 rows x 9 columns]

In [4]:
scaler= MinMaxScaler()
scale = scaler.fit_transform(df.iloc[:,:-1])
scale

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [5]:
binarizer=Binarizer(threshold=0.0)
binary=binarizer.fit_transform(df.iloc[:,:-1])
binary

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [42]:
df1=pd.read_csv("C:/Users/rajpu/OneDrive/Desktop/b/DataProcessing.csv")
df1

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [6]:
Standard=StandardScaler()
stand=Standard.fit_transform(df.iloc[:,:-1])
stand

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [43]:
print(pd.DataFrame(scale, columns=df.columns[:-1]).head())
print(pd.DataFrame(binary, columns=df.columns[:-1]).head())
print(pd.DataFrame(stand, columns=df.columns[:-1]).head())

   Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   

   DiabetesPedigreeFunction       Age  
0                  0.234415  0.483333  
1                  0.116567  0.166667  
2                  0.253629  0.183333  
3                  0.038002  0.000000  
4                  0.943638  0.200000  
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0          1.0      1.0            1.0            1.0      0.0  1.0   
1          1.0      1.0            1.0            1.0      0.0  1.0   
2          1.0      1.0            1.0            0.0      0.0  1.0   
3      

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes

In [59]:
X = df1.drop(columns=['Online Shopper'])
Y = df1['Online Shopper']

In [55]:
imputer = SimpleImputer(strategy='mean')
df1["Income"]= imputer.fit_transform(df1[["Income"]])

df1["Age"]= imputer.fit_transform(df1[["Age"]])
df1

Region        Age        Income Online Shopper  RegionEncoded  Brazil  \
0   India  49.000000  86400.000000             No              2       0   
1  Brazil  32.000000  57600.000000            Yes              1       1   
2     USA  35.000000  64800.000000             No              3       0   
3  Brazil  43.000000  73200.000000             No              1       1   
4     USA  45.000000  76533.333333            Yes              3       0   
5   India  40.000000  69600.000000            Yes              2       0   
6  Brazil  43.777778  62400.000000             No              1       1   
7   India  53.000000  94800.000000            Yes              2       0   
8     USA  55.000000  99600.000000             No              3       0   
9   India  42.000000  80400.000000            Yes              2       0   

   India  USA  
0      1    0  
1      0    0  
2      0    1  
3      0    0  
4      0    1  
5      1    0  
6      0    0  
7      1    0  
8      0    1  
9      1    0

In [56]:
label_encoder = LabelEncoder()
x=label_encoder.fit_transform(df1['Region'])
print(x+1)

[2 1 3 1 3 2 1 2 3 2]


In [62]:
y=label_encoder.fit_transform(df1['Online Shopper'])
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [63]:
label_encoder = LabelEncoder()

code = label_encoder.fit_transform(df1['Region'])
df1['RegionEncoded'] = (code + 1)

df1['Brazil'] = 0
df1['India'] = 0
df1['USA'] = 0

df1.loc[df1['RegionEncoded'] == 1, 'Brazil'] = 1
df1.loc[df1['RegionEncoded'] == 2, 'India'] = 1
df1.loc[df1['RegionEncoded'] == 3, 'USA'] = 1
y = label_encoder.fit_transform(df1['Online Shopper'])
df1['OnlineShopperEncoded'] = y
df1

Region        Age        Income Online Shopper  RegionEncoded  Brazil  \
0   India  49.000000  86400.000000             No              2       0   
1  Brazil  32.000000  57600.000000            Yes              1       1   
2     USA  35.000000  64800.000000             No              3       0   
3  Brazil  43.000000  73200.000000             No              1       1   
4     USA  45.000000  76533.333333            Yes              3       0   
5   India  40.000000  69600.000000            Yes              2       0   
6  Brazil  43.777778  62400.000000             No              1       1   
7   India  53.000000  94800.000000            Yes              2       0   
8     USA  55.000000  99600.000000             No              3       0   
9   India  42.000000  80400.000000            Yes              2       0   

   India  USA  OnlineShopperEncoded  
0      1    0                     0  
1      0    0                     1  
2      0    1                     0  
3      0    0                     0  
4      0    1                     1  
5      1    0                     1  
6      0    0                     0  
7      1    0                     1  
8      0    1                     0  
9      1    0                     1

In [ ]:
df1

In [22]:
X['Region_India'] = X['Region'].apply(lambda x: (x & 4) >> 2)
X['Region_Brazil'] = X['Region'].apply(lambda x: (x & 2) >> 1)
X['Region_USA'] = X['Region'].apply(lambda x: x & 1)


In [23]:
X['Online Shopper'] = (Y == 'Yes').astype(int)
X = X.drop(columns=['Region'])

In [24]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [25]:
print(X.head())
print(Y.head())
print(pd.DataFrame(X_scaled, columns=X.columns).head())

    Age        Income  Region_India  Region_Brazil  Region_USA  Online Shopper
0  49.0  86400.000000             0              0           1               0
1  32.0  57600.000000             0              0           0               1
2  35.0  64800.000000             0              1           0               0
3  43.0  73200.000000             0              0           0               0
4  45.0  76533.333333             0              1           0               1
0     No
1    Yes
2     No
3     No
4    Yes
Name: Online Shopper, dtype: object
        Age    Income  Region_India  Region_Brazil  Region_USA  Online Shopper
0  0.758874  0.749473           0.0      -0.654654    1.224745            -1.0
1 -1.711504 -1.438178           0.0      -0.654654   -0.816497             1.0
2 -1.275555 -0.891265           0.0       1.527525   -0.816497            -1.0
3 -0.113024 -0.253200           0.0      -0.654654   -0.816497            -1.0
4  0.177609  0.000000           0.0       1.527525